version: '3.9'

services:
  nodejs:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: scratchpay-node
    volumes:
      - .:/node_app/app
    command: /bin/sh -c "chmod +x entrypoint.sh && /node_app/app/entrypoint.sh"
    env_file:
      - .env

  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    container_name: scratchpay-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs

