on: 
  push:
    branches:
      - master
name: 🚀 Deploy api on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 18.14
      uses: actions/setup-node@v2
      with:
        node-version: '18.14'
      
    - name: 🔨 Build Project
      run: npm ci
    
    - name: 🔨 Run all tests
      run: npm test
